version: "3"
services:
    app:
        restart: always
        build: .
        container_name: app
        command: bash -c "gunicorn -c ./gunicorn.conf.py manage:app"
        expose:
            - "8000"
        networks:
            - web_network
    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:8009"
        networks:
            - web_network
networks:
    web_network:
        driver: bridge
